name: Fuzzing with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
  # Run the cron job through the week Mon-Fri at 3PM.
    - cron: "0 15 * * 1-5"

jobs:
  runscript:
    name: Build & run Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Call build.sh script
        run: |
                 chmod +x ${GITHUB_WORKSPACE}/build.sh
                 ${GITHUB_WORKSPACE}/build.sh
        shell: bash
      
      - name: Run Docker container
        run: |
                  chmod +x ${GITHUB_WORKSPACE}/run.sh
                  echo "ARTI=${GITHUB_WORKSPACE}/run.sh" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v3
        with:
          name: fuzz_artifact
          path: "${{ env.ARTI }}"
